# -*- coding: utf-8 -*-
"""
Default seed data for "Super PDP XML Template" and "Super PDP XML Field
Mapping". Ported directly from the field choices that used to be
hardcoded in ubl_builder.py, plus two fields the sample XML has that
the old hardcoded builder didn't emit yet: Delivery/ActualDeliveryDate
and the buyer's PartyIdentification/ID.

Rows with erpnext_doctype/erpnext_field left blank and transformation
"Computed by Engine" are values xml_mapper.py derives itself (line
index, tax category id/percent, tax subtotal amounts, SIREN-from-SIRET)
rather than copying a single ERPNext field - they're not "unmapped",
just not a 1:1 field copy. Rows left fully blank with required=0 are
genuinely unmapped by default (e.g. Delivery date - ERPNext's Sales
Invoice has no standard delivery-date field) and are omitted from the
generated XML unless an admin configures a source.
"""

DEFAULT_TEMPLATE_NAME = "EN16931 UBL (SuperPDP sample)"

# Each row: xml_path (relative to <Invoice>, "@attr" suffix for attributes),
# scope, erpnext_doctype, erpnext_field, transformation, required, notes.
DEFAULT_MAPPING_ROWS = [
	# --- Header ---------------------------------------------------------
	dict(xml_path="ID", scope="Invoice", erpnext_doctype="Sales Invoice", erpnext_field="name",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="IssueDate", scope="Invoice", erpnext_doctype="Sales Invoice", erpnext_field="posting_date",
		data_type="Date", required=1, transformation="Date (YYYY-MM-DD)"),
	dict(xml_path="DueDate", scope="Invoice", erpnext_doctype="Sales Invoice", erpnext_field="due_date",
		data_type="Date", required=0, transformation="Date (YYYY-MM-DD)",
		notes="Falls back to Issue Date if the invoice has none."),
	dict(xml_path="InvoiceTypeCode", scope="Invoice", erpnext_doctype="Sales Invoice", erpnext_field="is_return",
		data_type="Select", required=1, transformation="Invoice Type Code (380/381)"),
	dict(xml_path="DocumentCurrencyCode", scope="Invoice", erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Currency", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="Note", scope="Note", erpnext_doctype="Sales Invoice", erpnext_field="terms",
		data_type="Text", required=0, transformation="Strip HTML",
		notes="Optional. Left unmapped sends no <Note> elements."),

	# --- Seller (AccountingSupplierParty) -------------------------------
	dict(xml_path="AccountingSupplierParty/Party/EndpointID", scope="Invoice",
		erpnext_doctype="Super PDP Settings", erpnext_field="seller_siret",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="AccountingSupplierParty/Party/EndpointID@schemeID", scope="Invoice",
		is_attribute=1, attribute_name="schemeID",
		data_type="Text", required=1, transformation="Static Value", static_value="0225"),
	dict(xml_path="AccountingSupplierParty/Party/PostalAddress/Country/IdentificationCode", scope="Invoice",
		erpnext_doctype="Company", erpnext_field="country",
		data_type="Text", required=0, transformation="Country Code (ISO)"),
	dict(xml_path="AccountingSupplierParty/Party/PartyTaxScheme/CompanyID", scope="Invoice",
		erpnext_doctype="Company", erpnext_field="tax_id",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="AccountingSupplierParty/Party/PartyLegalEntity/RegistrationName", scope="Invoice",
		erpnext_doctype="Company", erpnext_field="company_name",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="AccountingSupplierParty/Party/PartyLegalEntity/CompanyID", scope="Invoice",
		erpnext_doctype="Super PDP Settings", erpnext_field="seller_siret",
		data_type="Text", required=1, transformation="SIREN from SIRET"),
	dict(xml_path="AccountingSupplierParty/Party/PartyLegalEntity/CompanyID@schemeID", scope="Invoice",
		is_attribute=1, attribute_name="schemeID",
		data_type="Text", required=1, transformation="Static Value", static_value="0002"),

	# --- Buyer (AccountingCustomerParty) --------------------------------
	dict(xml_path="AccountingCustomerParty/Party/EndpointID", scope="Invoice",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=1, transformation="Computed by Engine",
		notes="Customer.custom_siret, falling back to Super PDP Settings > Default Buyer SIRET if empty."),
	dict(xml_path="AccountingCustomerParty/Party/EndpointID@schemeID", scope="Invoice",
		is_attribute=1, attribute_name="schemeID",
		data_type="Text", required=1, transformation="Static Value", static_value="0225"),
	dict(xml_path="AccountingCustomerParty/Party/PartyIdentification/ID", scope="Invoice",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=0, transformation="Computed by Engine",
		notes="Mirrors the buyer's SIREN, same as PartyLegalEntity/CompanyID below."),
	dict(xml_path="AccountingCustomerParty/Party/PartyIdentification/ID@schemeID", scope="Invoice",
		is_attribute=1, attribute_name="schemeID",
		data_type="Text", required=0, transformation="Static Value", static_value="0225"),
	dict(xml_path="AccountingCustomerParty/Party/PostalAddress/Country/IdentificationCode", scope="Invoice",
		erpnext_doctype="Customer", erpnext_field="territory",
		data_type="Text", required=0, transformation="Country Code (ISO)"),
	dict(xml_path="AccountingCustomerParty/Party/PartyTaxScheme/CompanyID", scope="Invoice",
		erpnext_doctype="Customer", erpnext_field="tax_id",
		data_type="Text", required=0, transformation="None"),
	dict(xml_path="AccountingCustomerParty/Party/PartyLegalEntity/RegistrationName", scope="Invoice",
		erpnext_doctype="Customer", erpnext_field="customer_name",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="AccountingCustomerParty/Party/PartyLegalEntity/CompanyID", scope="Invoice",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=1, transformation="Computed by Engine",
		notes="SIREN derived from Customer.custom_siret (or the Settings fallback)."),
	dict(xml_path="AccountingCustomerParty/Party/PartyLegalEntity/CompanyID@schemeID", scope="Invoice",
		is_attribute=1, attribute_name="schemeID",
		data_type="Text", required=1, transformation="Static Value", static_value="0002"),

	# --- Delivery (optional - no standard ERPNext Sales Invoice field) --
	dict(xml_path="Delivery/ActualDeliveryDate", scope="Invoice",
		erpnext_doctype="", erpnext_field="",
		data_type="Date", required=0, transformation="Date (YYYY-MM-DD)",
		notes="No standard ERPNext field. Configure one (e.g. a custom field) if you need this; "
			"left unmapped, the whole <Delivery> block is omitted."),
	dict(xml_path="Delivery/DeliveryLocation/Address/Country/IdentificationCode", scope="Invoice",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=0, transformation="Country Code (ISO)",
		notes="No standard ERPNext field. Configure one if you need this."),

	# --- TaxTotal (overall) ---------------------------------------------
	dict(xml_path="TaxTotal/TaxAmount", scope="Invoice",
		erpnext_doctype="Sales Invoice", erpnext_field="total_taxes_and_charges",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="TaxTotal/TaxAmount@currencyID", scope="Invoice",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),

	# --- TaxTotal/TaxSubtotal (repeats per distinct VAT rate) -----------
	dict(xml_path="TaxTotal/TaxSubtotal/TaxableAmount", scope="TaxSubtotal",
		erpnext_doctype="", erpnext_field="",
		data_type="Currency", required=1, transformation="Computed by Engine",
		notes="Sum of line net amounts sharing this VAT rate."),
	dict(xml_path="TaxTotal/TaxSubtotal/TaxAmount", scope="TaxSubtotal",
		erpnext_doctype="", erpnext_field="",
		data_type="Currency", required=1, transformation="Computed by Engine",
		notes="Taxable amount x rate for this VAT rate group."),
	dict(xml_path="TaxTotal/TaxSubtotal/TaxAmount@currencyID", scope="TaxSubtotal",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="TaxTotal/TaxSubtotal/TaxableAmount@currencyID", scope="TaxSubtotal",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="TaxTotal/TaxSubtotal/TaxCategory/ID", scope="TaxSubtotal",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=1, transformation="Computed by Engine",
		notes='"S" (standard) or "Z" (zero-rated) depending on the rate.'),
	dict(xml_path="TaxTotal/TaxSubtotal/TaxCategory/Percent", scope="TaxSubtotal",
		erpnext_doctype="", erpnext_field="",
		data_type="Percent", required=1, transformation="Computed by Engine"),

	# --- LegalMonetaryTotal ----------------------------------------------
	dict(xml_path="LegalMonetaryTotal/LineExtensionAmount", scope="Invoice",
		erpnext_doctype="Sales Invoice", erpnext_field="net_total",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="LegalMonetaryTotal/LineExtensionAmount@currencyID", scope="Invoice",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="LegalMonetaryTotal/TaxExclusiveAmount", scope="Invoice",
		erpnext_doctype="Sales Invoice", erpnext_field="net_total",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="LegalMonetaryTotal/TaxExclusiveAmount@currencyID", scope="Invoice",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="LegalMonetaryTotal/TaxInclusiveAmount", scope="Invoice",
		erpnext_doctype="Sales Invoice", erpnext_field="grand_total",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="LegalMonetaryTotal/TaxInclusiveAmount@currencyID", scope="Invoice",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="LegalMonetaryTotal/PayableAmount", scope="Invoice",
		erpnext_doctype="Sales Invoice", erpnext_field="grand_total",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="LegalMonetaryTotal/PayableAmount@currencyID", scope="Invoice",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),

	# --- InvoiceLine (repeats per Sales Invoice Item) --------------------
	dict(xml_path="InvoiceLine/ID", scope="InvoiceLine",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=1, transformation="Computed by Engine",
		notes="Sequential line number (001, 002, ...)."),
	dict(xml_path="InvoiceLine/InvoicedQuantity", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="qty",
		data_type="Number", required=1, transformation="Number (3 decimals)"),
	dict(xml_path="InvoiceLine/InvoicedQuantity@unitCode", scope="InvoiceLine",
		is_attribute=1, attribute_name="unitCode",
		erpnext_doctype="Sales Invoice Item", erpnext_field="uom",
		data_type="Text", required=1, transformation="UOM Code (UN/ECE)"),
	dict(xml_path="InvoiceLine/LineExtensionAmount", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="net_amount",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="InvoiceLine/LineExtensionAmount@currencyID", scope="InvoiceLine",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
	dict(xml_path="InvoiceLine/Item/Name", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="item_name",
		data_type="Text", required=1, transformation="None"),
	dict(xml_path="InvoiceLine/Item/Description", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="description",
		data_type="Text", required=0, transformation="Strip HTML",
		notes="Omitted when identical to Item/Name."),
	dict(xml_path="InvoiceLine/Item/ClassifiedTaxCategory/ID", scope="InvoiceLine",
		erpnext_doctype="", erpnext_field="",
		data_type="Text", required=1, transformation="Computed by Engine"),
	dict(xml_path="InvoiceLine/Item/ClassifiedTaxCategory/Percent", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="item_tax_rate",
		data_type="Percent", required=1, transformation="Computed by Engine",
		notes="Sum of this line's item_tax_rate components; falls back to the invoice's overall rate."),
	dict(xml_path="InvoiceLine/Price/PriceAmount", scope="InvoiceLine",
		erpnext_doctype="Sales Invoice Item", erpnext_field="rate",
		data_type="Currency", required=1, transformation="Number (2 decimals)"),
	dict(xml_path="InvoiceLine/Price/PriceAmount@currencyID", scope="InvoiceLine",
		is_attribute=1, attribute_name="currencyID",
		erpnext_doctype="Sales Invoice", erpnext_field="currency",
		data_type="Text", required=1, transformation="Currency Code (ISO)"),
]
